config/routes.rb
Rails.application.routes.draw do
    root   'static_pages#home'
    get    '/admin',        to: 'admin#tasks'
    get    '/conferences',  to: 'conferences#index'
    get    '/teams',        to: 'teams#index'
    get    '/seasons',      to: 'seasons#index'
    post   '/get_team_seasons', to: 'admin#get_team_seasons'
    post   '/get_games',    to: 'admin#get_games'
    get    '/get_teams',    to: 'admin#get_teams'
    get    '/get players',  to: 'admin#get_players'
    resources :teams, only: [:index, :show]
    resources :conferences, only: [:index, :show]
    resources :seasons, only: [:index, :show]
    resources :games, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conference.rb
class Conference < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :teams
  has_many :team_seasons
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :away_team_season, :class_name => 'TeamSeason', :foreign_key => 'away_team_season_id', :optional => true
  belongs_to :home_team_season, :class_name => 'TeamSeason', :foreign_key => 'home_team_season_id', :optional => true
  belongs_to :home_team, :class_name => 'Team', :foreign_key => 'home_team_id', :optional => true
  belongs_to :away_team, :class_name => 'Team', :foreign_key => 'away_team_id', :optional => true
  belongs_to :season
end

app/models/player.rb
class Player < ApplicationRecord
  validates :espn_id, uniqueness: true
  belongs_to :team
end

app/models/season.rb
class Season < ApplicationRecord
  before_save :set_current
  validates :start_year, presence: true, uniqueness: true
  has_many :games
  has_many :team_seasons
  
  private
    def set_current
      Season.where.not(id: id).update_all(current: false)
    end
end

app/models/team.rb
class Team < ApplicationRecord
  validates :school, presence: true, uniqueness: { case_sensitive: false }
  validates :espn_id, uniqueness: true
  belongs_to :conference
  has_many :players
  has_many :team_seasons
  has_many :home_games, :class_name => 'Game', :foreign_key => 'home_team_id'
  has_many :away_games, :class_name => 'Game', :foreign_key => 'away_team_id'
end

app/models/team_game.rb
class TeamGame < ApplicationRecord
  belongs_to :game
  belongs_to :team
  belongs_to :team_season_id
  belongs_to :opponent, :class_name => 'Team', :foreign_key => 'opponent_id', :optional => true
  belongs_to :opponent_team_season, :class_name => 'TeamSeason', :foreign_key =>'opponent_team_season_id', :optional => true
end

app/models/team_season.rb
class TeamSeason < ApplicationRecord
  belongs_to :team
  belongs_to :conference
  belongs_to :season
  has_many :home_games, :class_name => 'Game', :foreign_key => 'home_team_season_id'
  has_many :away_games, :class_name => 'Game', :foreign_key => 'away_team_season_id'
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  validates :email, presence: true, uniqueness: { case_sensitive: false}
  has_secure_password
end

app/controllers/admin_controller.rb
require 'nokogiri'
require 'open-uri'

class AdminController < ApplicationController
  
  def tasks
    
  end
  
  
  # Seeds the database with all teams and conferences. Your conferences should first be loaded using db:seed
  
  def get_teams
    doc = Nokogiri::HTML(open("http://www.espn.com/mens-college-basketball/teams"))
    conferences = doc.css("div.mod-teams-list-medium")
    
    # Cycle through conferences filling in the name of each team along with their homepage url
    x = 1
    conferences.each do |conference|
      conf = Conference.find_or_initialize_by(name: conference.css("div.mod-header h4").text)
      conf.id = x
      conf.save
      teams = conference.css("ul li")
      y = 0 
      teams.each do |row|
        team_link = row.css("a.bi")
        team_name = team_link.text
        team_url = team_link[0]['href']
        team = Team.find_or_initialize_by(school: team_name)
        if team
          team.conference_id = x
          team.home_url = team_url
          team.save
        else
          print row
        end
      end
      x += 1
    end
    # Visit each team URL to get the rest of the team info and correct team name
    Team.all.each do |new_team|
      doc = Nokogiri::HTML(open(new_team.home_url))
      header = doc.css("div.global-nav-container ul.first-group")
      school = header.css("li.team-name span.link-text-short").text
      long_name = header.css("li.team-name span.link-text").text
      logo = header.css("span.brand-logo img").attr('src').to_s
      long_name.slice! school
      long_name.strip!
      logo.slice! "&h=150&w=150"
      new_team.school = school
      new_team.nickname = long_name
      new_team.logo_url = logo
      new_team.save
    end
    redirect_to teams_path
  end
  
  # Seed database with the roster for each team.
  def get_players
    Team.all.each do |team|
      loc = team.home_url.index('/_/')
      url = team.home_url.insert(loc, '/roster')
      doc = Nokogiri::HTML(open(url))
      players = doc.css('div.mod-content tr.oddrow, div.mod-content tr.evenrow')
      players.each do |player|
        player_url = player.css('td a').attr('href').to_s
        espn_id = player_url[player_url.index('/_/id/') + 6, 7]
        name = player.css('td')[1].text
        height = player.css('td')[3].text
        height_array = height.split('-')
        height = (height_array.first.to_i * 12 ) + height_array.last.to_i
        new_player = Player.find_or_initialize_by(espn_id: espn_id)
        new_player.team = team
        new_player.number = player.css('td')[0].text
        new_player.first_name = name.rpartition(' ').first
        new_player.last_name = name.rpartition(' ').last
        new_player.position = player.css('td')[2].text
        new_player.height = height
        new_player.weight = player.css('td')[4].text
        new_player.year = player.css('td')[5].text
        new_player.hometown = player.css('td')[6].text
        new_player.save
      end
    end
    redirect_to teams_path  
  end
  
  def get_games
    url_root = "https://www.ncaa.com/scoreboard/basketball-men/d1/"
    start_date = Date.civil(params[:start_date][:year].to_i, params[:start_date][:month].to_i, params[:start_date][:day].to_i)
    end_date = Date.civil(params[:end_date][:year].to_i, params[:end_date][:month].to_i, params[:end_date][:day].to_i)
    start_url = url_root + start_date.strftime('%Y/%m/%d')
    if end_date >= start_date 
      (start_date..end_date).each do |date|
        begin
          date_url = url_root + date.strftime('%Y/%m/%d')
          doc = Nokogiri::HTML(open(date_url))
        rescue OpenURI::HTTPError => e
          if e.message == '404 Not Found'
            # handle 404 error
          else
            # handle other errors
          end
        end
      end
    else
      redirect_to admin_path
    end
    redirect_to teams_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    if params[:date]
      date = Date.strptime(params[:date], '%Y%m%d')
      @games = Game.where(date: date).all
    else
      @games = Game.where(date: Date.today).all
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def index
    @seasons = Season.all
  end
  
  def show
    @season = Season.find(params[:id])
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all.order(:id)
  end
  
  def show
    @team = Team.find(params[:id])
    @team_season = TeamSeason.where(team: @team).first
    @home_games = @team_season.home_games
    @away_games = @team_season.away_games
    @games = @home_games + @away_games
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
  # returns current season if any
  def current_season
    if @current_season
      @current_season
    else
      @current_season = Season.where(current: true).first
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/games/index.html.erb
<%= link_to "Previous Day", games_path(date: (params[:date].to_i - 1).to_s) %>
<%= link_to "Next Day", games_path(date: (params[:date].to_i + 1).to_s) %>
<table>
  <thead>
    <tr>
      <th>ESPN ID</th>
      <th>Date</th>
      <th>Home Team</th>
      <th>Away Team</th>
      <th>Score</th>
      <th>Neutral?</th>
    </tr>
  </thead>
  <tbody>
    <% @games.all.each do |game| %>
    <tr>
      <td><%= game.espn_id %></td>
      <td><%= game.date %></td>
      <% if game.home_team %>
        <td><%= link_to game.home_team_name, game.home_team %></td>
      <% else %>
        <td><%= game.home_team_name %></td>
      <% end %>
      <% if game.away_team %>
        <td><%= link_to game.away_team_name, game.away_team %></td>
      <% else %>
        <td><%= game.away_team_name %></td>
      <% end %>
      <td><%= game.home_score.to_s + "-" + game.away_score.to_s %></td>
      <td><%= game.neutral %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/seasons/index.html.erb
<h1>All Seasons</h1>
<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Start Year</th>
      <th>End Year</th>
      <th>Description</th>
      <th>Start Date</th>
      <th>Regular Season End Date</th>
      <th>Championship Date</th>
    </tr>
  </thead>
  <tbody>
    <% @seasons.each do |season| %>
      <tr>
        <td><%= link_to season.id, season %></td>
        <td><%= season.start_year %></td>
        <td><%= season.end_year %></td>
        <td><%= season.description %></td>
        <td><%= season.start_date %></td>
        <td><%= season.regular_season_end_date %></td>
        <td><%= season.championship_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/seasons/show.html.erb
<table>
  <thead>
    <tr>
      <th>ESPN ID</th>
      <th>Date</th>
      <th>Home Team</th>
      <th>Away Team</th>
      <th>Score</th>
      <th>Neutral?</th>
    </tr>
  </thead>
  <tbody>
    <% @season.games.all.each do |game| %>
    <tr>
      <td><%= game.espn_id %></td>
      <td><%= game.date %></td>
      <td><%= game.home_team_name %></td>
      <td><%= game.away_team_name %></td>
      <td><%= game.home_score.to_s + "-" + game.away_score.to_s %></td>
      <td><%= game.neutral %></td>
    </tr>
    <% end %>
  </tbody>
</table>